### ISSUE TITLE
No proton versions found

### ISSUE THREAD

**Issue by webmaster-exit-1** [Termuellinator/Proton-Community-Updater#2]
When choosing GloriousEggroll, or TKG,  I get this:
![image](https://github.com/Termuellinator/Proton-Community-Updater/assets/98633966/4d2e5c34-3583-4e53-ba02-2b715c8eadc6)

**Comment by Termuellinator** [comment]
I just double-checked, the URLs haven't changed and it still works here. I would guess that your IP-range is has been rate limited or something of the likes. So it should work again at a later time. To verify you could try to access `https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases` or `https://api.github.com/repos/Frogging-Family/wine-tkg-git/releases` via curl or browser and see if it is also unavailable there.

**Comment by webmaster-exit-1** [comment]
Well, I feel dumb. Thank you for helping me solve my cacert.crt directory. My bad. 
For others that may have this issue, check which directory your program is getting the cacert from.
This error was my fault, not the devs or his code.
![image](https://github.com/Termuellinator/Proton-Community-Updater/assets/98633966/85deb0bb-9f35-4240-a6a2-9d5c0f76686a)
everything works now.
